version: '3.8'

services:
  bot:
    build: .
    container_name: docs_telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./downloads:/app/bot/downloads
      - ./output:/app/bot/output
